import type { Recipe } from "../recommender/types.js";

/** Recorded/sample responses — used in dev + ALL tests so we never burn Spoonacular quota. */
export const MOCK_RECIPES: Recipe[] = [
  {
    id: "mock:1",
    source: "mock",
    title: "Tomato Basil Pasta",
    cuisine: "italian",
    cookTime: 25,
    spice: "mild",
    ingredients: ["pasta", "tomato", "basil", "garlic", "olive oil"],
    instructions: [
      "Boil pasta until al dente; reserve 1 cup pasta water.",
      "Sauté garlic in olive oil, add tomatoes, simmer 10 min.",
      "Toss with pasta, basil, and pasta water. Serve.",
    ],
    nutrition: { calories: 520, protein: 15, carbs: 78, fat: 14 },
    pricePerServing: 1.2,
  },
  {
    id: "mock:2",
    source: "mock",
    title: "Veggie Rice Stir Fry",
    cuisine: "chinese",
    cookTime: 15,
    spice: "medium",
    ingredients: ["rice", "broccoli", "carrot", "soy sauce", "ginger"],
    instructions: [
      "Cook rice; set aside.",
      "Stir-fry veg 5 min, add soy + ginger.",
      "Toss with rice. Storage: fridge 3 days.",
    ],
    nutrition: { calories: 410, protein: 10, carbs: 72, fat: 7 },
    pricePerServing: 1.0,
  },
  {
    id: "mock:3",
    source: "mock",
    title: "Peanut Chicken Noodles",
    cuisine: "thai",
    cookTime: 20,
    spice: "hot",
    ingredients: ["noodles", "chicken", "peanut butter", "soy sauce", "chili"],
    instructions: ["Cook noodles.", "Whisk peanut sauce.", "Toss with chicken."],
    nutrition: { calories: 640, protein: 32, carbs: 60, fat: 28 },
    pricePerServing: 1.8,
  },
  {
    id: "mock:4",
    source: "mock",
    title: "Creamy Mushroom Pasta",
    cuisine: "italian",
    cookTime: 30,
    spice: "mild",
    ingredients: ["pasta", "mushroom", "milk", "parmesan", "butter"],
    instructions: ["Sauté mushrooms.", "Add milk + parmesan.", "Toss with pasta."],
    nutrition: { calories: 580, protein: 18, carbs: 65, fat: 26 },
    pricePerServing: 2.2,
  },
  {
    id: "mock:5",
    source: "mock",
    title: "Spicy Black Bean Tacos",
    cuisine: "mexican",
    cookTime: 20,
    spice: "hot",
    ingredients: ["tortilla", "black beans", "tomato", "onion", "chili"],
    instructions: ["Warm beans with spices.", "Char tortillas.", "Assemble tacos."],
    nutrition: { calories: 450, protein: 16, carbs: 68, fat: 10 },
    pricePerServing: 1.1,
  },
  {
    id: "mock:6",
    source: "mock",
    title: "Lentil Tomato Soup",
    cuisine: "indian",
    cookTime: 35,
    spice: "medium",
    ingredients: ["lentils", "tomato", "onion", "cumin", "turmeric"],
    instructions: ["Sauté onion + spices.", "Add lentils + tomato + water.", "Simmer 25 min."],
    nutrition: { calories: 380, protein: 18, carbs: 55, fat: 6 },
    pricePerServing: 0.8,
  },
  {
    id: "mock:7",
    source: "mock",
    title: "Pork Fried Rice",
    cuisine: "chinese",
    cookTime: 20,
    spice: "mild",
    ingredients: ["rice", "pork sausage", "egg", "soy sauce", "peas"],
    instructions: ["Fry pork.", "Add rice + peas + soy.", "Scramble in egg."],
    nutrition: { calories: 610, protein: 24, carbs: 62, fat: 26 },
    pricePerServing: 1.6,
  },
  {
    id: "mock:8",
    source: "mock",
    title: "Chickpea Curry with Rice",
    cuisine: "indian",
    cookTime: 30,
    spice: "medium",
    ingredients: ["chickpeas", "coconut milk", "tomato", "rice", "curry powder"],
    instructions: ["Sauté spices.", "Add chickpeas + tomato + coconut milk.", "Simmer; serve over rice."],
    nutrition: { calories: 540, protein: 16, carbs: 75, fat: 18 },
    pricePerServing: 1.3,
  },
  {
    id: "mock:9",
    source: "mock",
    title: "Vegetable Udon Soup",
    cuisine: "japanese",
    cookTime: 20,
    spice: "mild",
    ingredients: ["udon noodles", "carrot", "mushroom", "soy sauce", "ginger"],
    instructions: ["Simmer broth with ginger + soy.", "Add veg + udon.", "Cook 8 min. Serve hot."],
    nutrition: { calories: 420, protein: 12, carbs: 76, fat: 5 },
    pricePerServing: 1.4,
  },
  {
    id: "mock:10",
    source: "mock",
    title: "French Lentil Salad",
    cuisine: "french",
    cookTime: 25,
    spice: "mild",
    ingredients: ["lentils", "carrot", "onion", "feta", "olive oil"],
    instructions: ["Simmer lentils 20 min; drain.", "Dice veg; whisk oil + vinegar.", "Toss; top with feta."],
    nutrition: { calories: 390, protein: 17, carbs: 48, fat: 12 },
    pricePerServing: 1.5,
  },
  {
    id: "mock:11",
    source: "mock",
    title: "Mediterranean Chickpea Salad",
    cuisine: "mediterranean",
    cookTime: 15,
    spice: "mild",
    ingredients: ["chickpeas", "cucumber", "tomato", "olive oil", "lemon"],
    instructions: ["Rinse chickpeas.", "Chop veg.", "Toss with oil + lemon. Rest 10 min."],
    nutrition: { calories: 350, protein: 12, carbs: 45, fat: 11 },
    pricePerServing: 1.0,
  },
  {
    id: "mock:12",
    source: "mock",
    title: "American Black Bean Chili",
    cuisine: "american",
    cookTime: 35,
    spice: "medium",
    ingredients: ["black beans", "tomato", "onion", "corn", "chili powder"],
    instructions: ["Sauté onion + spices.", "Add beans + tomato + corn.", "Simmer 25 min."],
    nutrition: { calories: 430, protein: 18, carbs: 70, fat: 6 },
    pricePerServing: 0.9,
  },
  {
    id: "mock:13",
    source: "mock",
    title: "Middle Eastern Hummus Bowl",
    cuisine: "middle eastern",
    cookTime: 15,
    spice: "mild",
    ingredients: ["chickpeas", "tahini", "lemon", "garlic", "olive oil"],
    instructions: ["Blend chickpeas + tahini + lemon.", "Loosen with water.", "Top with oil; serve with veg."],
    nutrition: { calories: 380, protein: 13, carbs: 42, fat: 16 },
    pricePerServing: 1.1,
  },
  {
    id: "mock:14",
    source: "mock",
    title: "African Bean Stew",
    cuisine: "african",
    cookTime: 30,
    spice: "medium",
    ingredients: ["black-eyed peas", "tomato", "onion", "chili", "ginger"],
    instructions: ["Sauté onion + ginger + chili.", "Add peas + tomato + water.", "Simmer 20 min."],
    nutrition: { calories: 410, protein: 19, carbs: 62, fat: 5 },
    pricePerServing: 0.8,
  },
];
