import type { Recipe } from "../recommender/types.js";

/** Recorded/sample responses — used in dev + ALL tests so we never burn Spoonacular quota. */
export const MOCK_RECIPES: Recipe[] = [
  {
    id: "mock:1",
    source: "mock",
    title: "Tomato Basil Pasta",
    cuisine: "italian",
    cookTime: 25,
    spice: "mild",
    ingredients: ["pasta", "tomato", "basil", "garlic", "olive oil"],
    instructions: [
      "Boil pasta until al dente; reserve 1 cup pasta water.",
      "Sauté garlic in olive oil, add tomatoes, simmer 10 min.",
      "Toss with pasta, basil, and pasta water. Serve.",
    ],
    nutrition: { calories: 520, protein: 15, carbs: 78, fat: 14 },
  },
  {
    id: "mock:2",
    source: "mock",
    title: "Veggie Rice Stir Fry",
    cuisine: "chinese",
    cookTime: 15,
    spice: "medium",
    ingredients: ["rice", "broccoli", "carrot", "soy sauce", "ginger"],
    instructions: [
      "Cook rice; set aside.",
      "Stir-fry veg 5 min, add soy + ginger.",
      "Toss with rice. Storage: fridge 3 days.",
    ],
    nutrition: { calories: 410, protein: 10, carbs: 72, fat: 7 },
  },
  {
    id: "mock:3",
    source: "mock",
    title: "Peanut Chicken Noodles",
    cuisine: "thai",
    cookTime: 20,
    spice: "hot",
    ingredients: ["noodles", "chicken", "peanut butter", "soy sauce", "chili"],
    instructions: ["Cook noodles.", "Whisk peanut sauce.", "Toss with chicken."],
    nutrition: { calories: 640, protein: 32, carbs: 60, fat: 28 },
  },
  {
    id: "mock:4",
    source: "mock",
    title: "Creamy Mushroom Pasta",
    cuisine: "italian",
    cookTime: 30,
    spice: "mild",
    ingredients: ["pasta", "mushroom", "milk", "parmesan", "butter"],
    instructions: ["Sauté mushrooms.", "Add milk + parmesan.", "Toss with pasta."],
    nutrition: { calories: 580, protein: 18, carbs: 65, fat: 26 },
  },
  {
    id: "mock:5",
    source: "mock",
    title: "Spicy Black Bean Tacos",
    cuisine: "mexican",
    cookTime: 20,
    spice: "hot",
    ingredients: ["tortilla", "black beans", "tomato", "onion", "chili"],
    instructions: ["Warm beans with spices.", "Char tortillas.", "Assemble tacos."],
    nutrition: { calories: 450, protein: 16, carbs: 68, fat: 10 },
  },
  {
    id: "mock:6",
    source: "mock",
    title: "Lentil Tomato Soup",
    cuisine: "indian",
    cookTime: 35,
    spice: "medium",
    ingredients: ["lentils", "tomato", "onion", "cumin", "turmeric"],
    instructions: ["Sauté onion + spices.", "Add lentils + tomato + water.", "Simmer 25 min."],
    nutrition: { calories: 380, protein: 18, carbs: 55, fat: 6 },
  },
  {
    id: "mock:7",
    source: "mock",
    title: "Pork Fried Rice",
    cuisine: "chinese",
    cookTime: 20,
    spice: "mild",
    ingredients: ["rice", "pork sausage", "egg", "soy sauce", "peas"],
    instructions: ["Fry pork.", "Add rice + peas + soy.", "Scramble in egg."],
    nutrition: { calories: 610, protein: 24, carbs: 62, fat: 26 },
  },
  {
    id: "mock:8",
    source: "mock",
    title: "Chickpea Curry with Rice",
    cuisine: "indian",
    cookTime: 30,
    spice: "medium",
    ingredients: ["chickpeas", "coconut milk", "tomato", "rice", "curry powder"],
    instructions: ["Sauté spices.", "Add chickpeas + tomato + coconut milk.", "Simmer; serve over rice."],
    nutrition: { calories: 540, protein: 16, carbs: 75, fat: 18 },
  },
];
